name = "structures"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
description = "Some miscellaneous data structures for Gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "sporto", repo = "gleam-data-structures" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
